### PR TITLE
WIP (Help needed): Add switch to only download with wifi connection.

### PR DESCRIPTION
**Pull request by Y0ngg4n**
This adds a basic switch to the settings menu to only download music with wifi connection. But i need help with this to save to hive db and register the notifier with provider. Dont want to destroy the current models.

### CODE REVIEW

**Comment by Y0ngg4n** [comment]
@jmshrv could you help here?

**Comment by jmshrv** [comment]
Just pushed the stuff to save the setting in FinampSettings, you can access the value with `FinampSettingsHelper.finampSettings.onlyDownloadWithWifi`. I'll look at the other stuff tomorrow since I'm tired 🙃

**Comment by Y0ngg4n** [comment]
@jmshrv hey thank you thats great :partying_face: 
Have a nice day :)

**Comment by jmshrv** [comment]
Hi, sorry for the delay, I'm working through my pile of emails right now :)

`flutter_downloader` added support for only downloading via WiFi, it would be easier to handle it through there: https://pub.dev/documentation/flutter_downloader/latest/flutter_downloader/DownloadTask/allowCellular.html

We'll need to jump to a new version of flutter_downloader, it's been pinned on my own branch of it for a while. Shouldn't cause any issues, the fix in my branch has been merged into a release.

**Comment by Chaphasilor** [comment]
@Y0ngg4n do you want to try and update `flutter_downloader` and go through it instead? Otherwise I could try doing it myself :)

**Comment by Y0ngg4n** [comment]
@Chaphasilor currently i don´t have the capacities for it sorry :(

**Comment by Chaphasilor** [comment]
This will probably be superseded by #568, but I can still try to get this merged before the next version is released :)

**Comment by Y0ngg4n** [comment]
Na i think we can close this then if it is going to be superseeded.

**Comment by Chaphasilor** [comment]
I mean the other PR targets `redesign`, so for the people who don't want to switch to the beta version this would be nice. And I guess we can just keep your current `flutter_downloader`-based implementation, as that would be more stable than a fresh implementation...

I'll see if I have the time to fix the merge conflicts...

Oh and Merry Christmas! 🎄

**Comment by Y0ngg4n** [comment]
Ok i understand :thinking: would be nice. But this MR wasnt working either. 

And Merry Christmas to you too :)

**Comment by Chaphasilor** [comment]
@Y0ngg4n could you tell me what wasn't working? I'm not sure I have the capacity to fix it up, but if it's only a small-ish issue I might do it.  
Otherwise I'll probably close this PR instead an focus on the redesign for now 😅

**Comment by Y0ngg4n** [comment]
@Chaphasilor close it :)

**Pull request closed without merging**
