### PR TITLE
WIP: Delete Items from Playlist

### PR DESCRIPTION
**Pull request by Y0ngg4n**
@jmshrv maybe you could review it. 
i have created the Api Request, and it sends the API Request to the Jellyfin Server.
I get a 204 back but the item does not get removed from the Playlist. Am i doing something wrong?
```
--> DELETE https://media.example.com/Playlists/bba88a58b8687fe6d8b0c280cb7acd9b/Items?entryIds=ac8bb27d9796804cc40e5a5503f1bea8
I/flutter (15961): [Chopper/INFO] 2022-10-06 18:44:41.959262: Content-Type: application/json
I/flutter (15961): [Chopper/INFO] 2022-10-06 18:44:41.959753: X-Emby-Authorization: MediaBrowser UserId="USERID", Client="Finamp", Device="Bla", DeviceId="BLABLUP", Version="0.6.8"
I/flutter (15961): [Chopper/INFO] 2022-10-06 18:44:41.960282: X-Emby-Token: TOKEN
I/flutter (15961): [Chopper/INFO] 2022-10-06 18:44:41.961047: --> END DELETE
I/flutter (15961): [Chopper/INFO] 2022-10-06 18:44:42.768490: <-- 204 https://media.example.com/Playlists/bba88a58b8687fe6d8b0c280cb7acd9b/Items?entryIds=ac8bb27d9796804cc40e5a5503f1bea8

```

### CODE REVIEW

**Comment by jmshrv** [comment]
If you refresh the playlist by exiting and entering, does it delete? We'd probably have to implement a way of removing a tile from the list, which could be done by using a provider to store the current item shown in the album screen

**Comment by Y0ngg4n** [comment]
> If you refresh the playlist by exiting and entering, does it delete? We'd probably have to implement a way of removing a tile from the list, which could be done by using a provider to store the current item shown in the album screen

Nope it does not delete. Even if i view the Playist in browser.

**Comment by BhasherBEL** [comment]
As the function is now merged from another PR, I think this once should be closed.

**Comment by Y0ngg4n** [comment]
@BhasherBEL thanks

**Pull request closed without merging**
