### PR TITLE
minor player screen changes

### PR DESCRIPTION
**Pull request by Chaphasilor**
Some minor QoL improvements. Should probably rebase this to the regular redesign branch, as the changes are not related to the colors...

Also, the way the queue panel is created isn't ideal, it's basically just code repetition. I tried programmatically pressing the queue button instead, but couldn't get it to work. Would love to have some kind of method for that, which we can pass the current context and then open the panel through a simple function call!

### CODE REVIEW

**Comment by jmshrv** [comment]
These changes look good :)

We could add a function that calls `showModalBottomSheet` for us with the relevant settings. I'll merge this when it's rebased to `redesign` if you're happy with it

**Comment by Chaphasilor** [comment]
hmm, you can't rename a branch that's being referenced by a PR or the PR will be closed. TIL :D  
should be properly rebased now :)

**Comment by Chaphasilor** [comment]
Oh and if you could add that method you mentioned that would be great, I'm not totally sure yet how to handle the context...

**Comment by jmshrv** [comment]
Added the method, is this ready to merge?

**Comment by Chaphasilor** [comment]
Yes, looks good! 😁  
Thanks!

**Pull request merged**
