### PR TITLE
Add deletion of albums and songs

### PR DESCRIPTION
**Pull request by Y0ngg4n**
This PR Adds simple deletion of already downloaded albums and songs

### CODE REVIEW

**Comment by jmshrv** [comment]
Thanks for this :)

I've just added a push that makes items actually disappear when deleting, but there are a few issues before this is merged:

* The rest of the downloads screen doesn't update (such as the overview at the top, file sizes etc
* When deleting an album in offline mode, the album still shows in the album screen, which causes an error when opened as the album no longer exists

Both could be solved by doing some state management with Riverpod. For the 2nd one, this would mean hooking up the album list to use a central source of albums from Riverpod, which would be a pretty big task. I don't mind doing this, as it would also help with other issues like deleting albums in offline mode from the album screen (which I've disabled for the same reason).

**Comment by Y0ngg4n** [comment]
Hi thanks for your review. Sure would be nice if i could get some help from you and learn fron your project 🙂

Yes i have already seen that the list does not update caused by statelesswidget. But do not know how you handle states via hive. Quick side question wouldnt it be better to use isar?

**Comment by jmshrv** [comment]
Finamp gets the list of albums with the `JellyfinApiHelper` class, which simply returns once without any sort of live updating. Currently, downloaded songs are stored in Hive databases, as at the time Isar was still in development. #213 will replace this janky system of Hive databases with an Isar database which should make stuff much easier. For now, we can either:

* Add a provider that handles getting the albums and allows different bits of the app to modify the list
* Rework `JellyfinApiHelper` to return a listener on the database. I'd like to more cleanly separate online and offline mode, so maybe I'll consider this then.

**Comment by jmshrv** [comment]
Fixes #160

**Comment by Y0ngg4n** [comment]
Ok thank you for the explanation. So what do we have to do with this PR now?

**Comment by jmshrv** [comment]
I'll probably go with the stream option as it would be much easier than using providers, although I might change my mind mid-implementation as it would cause a lot of useless StreamBuilders in the code.

**Comment by Y0ngg4n** [comment]
Ok sounds good

**Comment by arthurlutz** [comment]
Looking forward to this feature. Do you need help testing it out ?

**Comment by Y0ngg4n** [comment]
No i have to first implement the missing parts. But i am currently short on time.

**Comment by Y0ngg4n** [comment]
@jmshrv i have tested it now and it seems to work just fine. anything we need to do here or can we just merge?

**Comment by jmshrv** [comment]
I'll merge this for now, the other improvements can come later

**Comment by Y0ngg4n** [comment]
@jmshrv thank you :)

**Comment by Y0ngg4n** [comment]
@jmshrv could we push out a new release?

**Comment by jmshrv** [comment]
Yeah, I'll make a new one as discussed in #371

**Pull request merged**
