### PR TITLE
Fix release order for appstream validation

### PR DESCRIPTION
**Pull request by baarkerlounger**
Needed to fix https://github.com/flathub/com.unicornsonlsd.finamp/pull/2

### CODE REVIEW

**Comment by Chaphasilor** [comment]
They really are picky 😅

While you're at it, you could also update the release date for 0.9.8, I had to take a guess on that one...

**Comment by baarkerlounger** [comment]
I don't make the rules :rofl: 

I think the date should probably point to the Finamp release date so have updated it to that.

**Comment by Chaphasilor** [comment]
Thanks! :)

**Comment by baarkerlounger** [comment]
@Chaphasilor mind updating the release assets?

**Comment by Chaphasilor** [comment]
done :)

**Pull request merged**
