### PR TITLE
[Redesign] Fix non-transcoded downloads + tweaks

### PR DESCRIPTION
**Pull request by Komodo5197**
Fixes the .song extension applied to all downloaded original songs, which breaks iOS playback.  Also includes a couple other random tweaks I had in the branch:

- A basic fix to the fast scroller accent issue by just ignoring any items with characters beyond z.
- Queue item padding tweak.
- Apply ''Prioritize cover" player setting to landscape mode as well as portrait.
- Just make airplay button white because it can't change theme when switching songs.

Tell me if you want a cleaner version.

### CODE REVIEW

**Comment by Chaphasilor** [comment]
Could you exclude the fast scroller tweaks? I'm working on a "proper" fix right now :)

And about the AirPlay button, what about putting it into some kind of builder that updates when the theme updates? Wouldn't that work?

**Comment by Komodo5197** [comment]
I can force it to animate by setting a key from the iconColor, I think.  But the performance implications of disposing and rebuilding a native widget for every frame of the theme animation seems questionable.  Maybe I can make it just jump at the transition start along with the album art?

**Comment by Chaphasilor** [comment]
Yeah, it doesn't have to be animated. Maybe you can use a stream from the current theme provider, which would trigger the theme animation.  
Let me know if you want to try that out first, or if I should merge the PR already!

**Comment by Komodo5197** [comment]
I put the icon into an animated switcher, so we only build two icons and just fade between them.  The docs say that opacity stuff works fine on native views, so hopefully this doesn't cause problems.

**Comment by Chaphasilor** [comment]
Thanks a ton. I can't test the iOS stuff either, let's just hope it works...

**Pull request merged**
