### PR TITLE
Adds a shortcut to system equalizer. (Only works on android)

### PR DESCRIPTION
**Pull request by Y0ngg4n**
Added a check if system is android

### CODE REVIEW

**Comment by jmshrv** [comment]
This isn't too useful imo, the user can get to their equaliser in their system settings. If I ever get around to #177, we could likely implement an equaliser in Finamp that will support all platforms

**Comment by Y0ngg4n** [comment]
Most People dont know about the system Equalizer. I dont know how we could implement it for all platforms.

**Comment by jmshrv** [comment]
If my plans to use GStreamer as a player backend work, we could implement it in the player: https://gstreamer.freedesktop.org/documentation/equalizer/index.html

Another thing to note is that not all Android skins have a system equaliser, and from quick look at the Equalizer package it looks like there isn't a way to determine this.

**Comment by Y0ngg4n** [comment]
ah ok thank you :)

**Comment by Y0ngg4n** [comment]
But i guess there is no gstreamer package we can use so we have to implement it our selves right?

**Comment by jmshrv** [comment]
Yeah, my initial idea is to make a just_audio implementation that uses GStreamer. It's pretty far off, but it'll be really nice once it's done.

**Pull request closed without merging**
