### PR TITLE
Airplay button redesign

### PR DESCRIPTION
**Pull request by ihatetoregister**
2nd try adding airplay button for ios, on redesign branch

tested ok on ios device

is the button placemement ok? also not sure what to do about the layout warning...

Simulator Screenshot - iPhone SE (3rd generation) - 2024-02-09 at 12 24 17

### CODE REVIEW

**Comment by ihatetoregister** [comment]
seems to be possible to change the color on the icon as well, maybe white should be more in line with the rest of the UI

                if (Platform.isIOS) AirPlayRoutePickerView(tintColor: Colors.white, activeTintColor: Colors.white),

also noted this flutter package contains some sketchy tracking package, not sure its intentional but I might need to look for alternatives or make fork

**Comment by Chaphasilor** [comment]
I don't see how that package is a privacy issue, do you have any details about that? If the build is working fine I have no problem with using it.  
I'll take a look at the tint color and overflow issues :)

**Comment by Chaphasilor** [comment]
Okay, I tried to improve the colors and fix the overflow issues, but I can't test it on Android, so I'm basically just guessing. Would be great if you could test it and send me a screenshot and maybe some logs if necessary.

**Comment by ihatetoregister** [comment]
Great, im on ios only here as well unfortunately, but tested on device and looks good. 

Screenshot 2024-02-10 at 07 56 48

**Comment by ihatetoregister** [comment]
Ok, just realized i just got the overflow issue on the simulator (iPhone SE 3rd gen), and it still appears. But it also appears on the unchanged redesign branch, so I guess that could be treated as separate issue. 

Simulator Screenshot - iPhone SE (3rd generation) - 2024-02-10 at 10 08 41

**Comment by Chaphasilor** [comment]
Okay, I added some padding to the button because it was slightly too close to the edge of the screen for my taste, but that's only a minor detail. Please give it another quick test to see that everything is still working as expected (and a screenshot wouldn't hurt so I can get an idea of how it looks now).  
Also, is the "active" state color fine? I chose Finamp's default blue, given that the original icon also was blue. But I'm not sure how that looks in practice.

I also improved the scaling logic for the player screen to better support small screens, could you please take another look at `redesign` with the iPhone SE3?

Once you give the final okay, I'll merge this in :)

**Comment by Chaphasilor** [comment]
@ihatetoregister so, should I merge this? Is everything working?

**Comment by ihatetoregister** [comment]
Sure, looks fine to me!

Active airplay button
Screenshot 2024-02-13 at 22 06 20

**Comment by ihatetoregister** [comment]
New snapshot of redesign branch looks fine on SE3 as well

Simulator Screenshot - iPhone SE (3rd generation) - 2024-02-13 at 23 00 38

**Comment by Chaphasilor** [comment]
Awesome, merged! Thanks a lot! 😁

**Pull request merged**
