### PR TITLE
Add music visualizer on currently playing song

### PR DESCRIPTION
**Pull request by Y0ngg4n**
Add this https://pub.dev/packages/mini_music_visualizer to the currently playing song

### CODE REVIEW

**Comment by jmshrv** [comment]
I feel like this is a bit redundant as the song list tile already changes the title colour for the currently playing song

**Comment by Y0ngg4n** [comment]
I dont think so because the animation is a movement, so it is easier for the eyes to spot the title. I personally had it often that i did not spot the song.

**Comment by Y0ngg4n** [comment]
ok so how to proceed with this? Close it?

**Comment by jmshrv** [comment]
It could be merged, I just need to have a look at the code since there may be a more efficient way of displaying it (I'm pretty sure SongListTile already has a StreamBuilder for the song title that we could expand)

**Comment by espector** [comment]
This looks like a nice visualization. Vote to add it :)

**Comment by Chaphasilor** [comment]
I'm also in favor of the change, although I'll probably end up putting it on top of the album cover in the song list tile to save some space...

**Comment by jmshrv** [comment]
Moved it about a bit, enabling/disabling the visualiser is now in SongListTIle. Also fixed merge conflicts and stuff. Only thing to do now is to hide the visualiser when the song is paused.

**Pull request merged**
