### PR TITLE
Remove from playlist

### PR DESCRIPTION
**Pull request by BhasherBEL**
This implement the "remove from playlist" button, fixing #340 and most of #347.
But I have two concerns:
 - When a music is delete, you need to update the playlist content to see it visually removed. Maybe you have an idea of how to update the list ?
 - When the last music is delete, you get an empty playlist. Trying to open a empty playing leads to the crash of the application. Even if an empty playlist isn't usually desirable, it could be sometime temporary. It could be useful to be able to display them ?

If you have any other concerns, feel free to ask fixes.

### CODE REVIEW

**Comment by jmshrv** [comment]
This looks good so far, is it intended to supercede #347?

* For getting rid of the song list tile, the simplest solution would probably be a callback function. I suggested using a provider in #347, but that is a pretty complex solution that is arguably less clean. It'd look something like `onDelete: () => setState({ items.removeAt(index) })`.
* There's probably some null check error happening, should be a simple fix

**Comment by BhasherBEL** [comment]
Yes, it's a reimplementation of #347.
 
I tried something like you suggest but sadly after 2 seconds (animation duration) the item come back and remove the last one. Here is a first implementation. I will try to fix the problem completely and also the empty playlist crash when I have time.

**Comment by BhasherBEL** [comment]
This should fix the problem. But I had to replace all `mutableItem` by `wiget.item` and delete the `late` item in `components/AlbumScreen/song_list_tile.dart`. The comment said it was used to change favourite property, but it seems to still work even with my fix.

**Comment by BhasherBEL** [comment]
This should fix the problems. The first commit is about visually remove items and the second prevents the app to crash when opening an empty playlist.

For the first one, I had to replace all `mutableItem` by `wiget.item` and delete the late item in `components/AlbumScreen/song_list_tile.dart`. The comment said it was used to change favourite property, but it seems to still work even with my fix.

Feel free to suggest any other change.

**Comment by BhasherBEL** [comment]
@jmshrv ?

**Comment by jmshrv** [comment]
Sorry, missed this in my emails :upside_down_face: 

The code looks good, I'll do a bit more testing in a bit (since this is quite a big PR) but from what I can see it should work well :)

**Comment by jmshrv** [comment]
Just did a few other things (described in the commit messages), merging now. Thanks for implementing this!

**Pull request merged**
