### PR TITLE
✨ Audio Loudness Normalization (Replay Gain)

### PR DESCRIPTION
**Pull request by Chaphasilor**
(This PR is based on #484 and should only be merged afterwards)

This adds LUFS-based loudness normalization ("replay gain"), based on https://github.com/jellyfin/jellyfin/pull/9222 and https://github.com/jellyfin/jellyfin/pull/10085.  
For this PR to have an effect the server has to be on the "unstable" release channel of Jellyfin. The feature will be released to the stable channel as part of Jellyfin 10.9.  
~~This currently only works on Android, because it uses [`AndroidLoudnessEnhancer`](https://pub.dev/documentation/just_audio/latest/just_audio/AndroidLoudnessEnhancer-class.html) which doesn't have an equivalent on iOS.~~ I'm looking into emulating this for iOS simply by changing the player's volume accordingly.

There's a new settings page for this, which lets the user customize the target LUFS (default is `-14.0`, like on i.e. Spotify), a factor which controls by how much the loudness should be changed towards the target LUFS (the "aggressiveness", default is `1.0`), and the normalization mode.  
For iOS and other non-Android platforms, there's also a setting that lets the user specify a base gain that is used for emulating proper output gain. This value should be negative, so that the volume can be increased to boost the volume of quiet tracks. The default is -5 dB (75% volume), which leaves some headroom but doesn't reduce the volume too much. My test library almost exclusively contained tracks that had a LUFS value greater than the default target of -14 LUFS, so a gain greater than 1 doesn't seem to be too common.

There are three modes:
- "Hybrid" (default): Tracks will be normalized based on each track's LUFS value, but when playing an album the album's LUFS value is used (only for tracks from the same album)
- "Tracks only": Normalization happens only based on the track's LUFS value, the album's LUFS value is ignored
- "Albums only": Normalization only happens when playing albums, based on that album's LUFS value

Screenshot_20231022-173137

### TODOs

- [x] Emulate gain changing on other platforms by modifying the player volume
- [ ] ~~Add feature detection so the setting is only available if the server supports it~~
  - Maybe add some kind of framework for feature detection in another PR?

### CODE REVIEW

**Comment by jmshrv** [comment]
The code in this PR looks good, I'd be happy to merge it :)

**Comment by Chaphasilor** [comment]
Ahh good catch, I added some code to handle that. If you could make sure I didn't breaking anything before you merge it that would be great 😅

**Comment by Titaniumtown** [comment]
Wanted to say that it's awesome this got merged, huge improvement to user experience! Thanks for your continued hard work @Chaphasilor!

**Comment by Chaphasilor** [comment]
Thanks @Titaniumtown! Were you able to try it out already? :)

**Comment by Titaniumtown** [comment]
> Thanks @Titaniumtown! Were you able to try it out already? :)

Yes I built it and tried it out, works like a charm.

**Pull request merged**
