### PR TITLE
Draft: Changing Player design

### PR DESCRIPTION
**Pull request by Y0ngg4n**
Changing the Player design like in the issue discussed.

### CODE REVIEW

**Comment by 7kayoh** [comment]
Just asking if possible, can we not have the song info in the now playing screen be contained in a chip component? I think it would look nicer if it’s in a button with no background.

**Comment by Y0ngg4n** [comment]
@7kayoh sure. It was just the way the other already implemented it on this branch.

**Comment by jmshrv** [comment]
I'm assuming this PR is meant to go into redesign instead of main?

**Comment by Y0ngg4n** [comment]
@jmshrv ah yeah sorry

**Pull request closed without merging**
