### PR TITLE
Add toggle to disable vibration #657

### PR DESCRIPTION
**Pull request by Ivanf1**
Hello!
This PR addresses issue #657.

As suggested by @Chaphasilor in [this comment](https://github.com/jmshrv/finamp/issues/657#issuecomment-2027025098) (if I understood correctly), I wrapped the vibration setting check in a class.

I will be waiting for feedback. Hope this can help!

### CODE REVIEW

**Comment by Chaphasilor** [comment]
Thanks for the PR!

The changes look very good overall, and are exactly what I had in mind!  
Would you mind renaming the class to `FeedbackHelper` (so we could theoretically support audio (etc.) feedback on platforms that don't support vibration in the future)?  

And another thing, please call the setting "*enable* vibration" and make it true by default. So that disabling the setting disables vibration. That makes a bit more sense compared to enabling a setting to disable something, just a minor usability improvement ^^

**Comment by Ivanf1** [comment]
Thanks for the feedback!

I implemented the requested changes. Let me know if there is more I can do.

**Comment by Chaphasilor** [comment]
Thanks, that looks perfect! I'll give it a try in a few minutes!

**Comment by Chaphasilor** [comment]
Merged, since everything is working just fine! Thank you!

**Pull request merged**
