### PR TITLE
[Redesign] Access sidebar via gesture

### PR DESCRIPTION
**Pull request by Komodo5197**
Allows accessing the sidebar by swiping right when on the leftmost tab of the music screen.

### CODE REVIEW

**Comment by Chaphasilor** [comment]
The gesture is definitely better than swiping from the edge of the screen, with all of the native gesture navigation now ^^

But in the current planned design for the home screen, the menu is moved to a popup (or maybe a bottom sheet to stay consistent) that is opened by tapping a button in the top right. Here's what I'm referring to:

Home Screen Concept Mockup

The cog (might be replaced with the user's profile picture) would open the menu, and it should be structured similar to Immich's:
image


So I'm not sure how long this change will survive / make sense 😅

**Comment by Komodo5197** [comment]
Yeah, I'm aware this might not last that long.  But I've found myself instinctively making this gesture an unreasonable amount of times, so I decided I might as well get it in until then.

**Comment by Chaphasilor** [comment]
Alright, I guess it won't hurt, and it works just fine in my testing ^^

**Comment by jmshrv** [comment]
Decided to disable this on iOS since it felt weird with the "bounce" at the end of lists, which Android doesn't have (7da719aa55dc020441b09b0f770fa87635789f14).

**Comment by jmshrv** [comment]
oh also that change will apply for macOS/Windows/Linux, I actually just enabled it for Android

**Comment by Chaphasilor** [comment]
@Komodo5197 aren't you on iOS? I guess you had your reasons for wanting the gesture? 😅

**Comment by Komodo5197** [comment]
Actually, my existing phone finally broke a month or two ago, and I ended up with an Android to replace it.  It's way larger, because apparently nobody manufactures reasonably sized phones anymore, which is presumably why I kept trying to get the sidebar open with a gesture instead of just using the button.

**Comment by Chaphasilor** [comment]
Ah okay. Yeah small phones are very hard to get ahold of. But I'm glad you were able to keep using Finamp! 😁

**Pull request merged**
