### PR TITLE
Changing Player design

### PR DESCRIPTION
**Pull request by Y0ngg4n**

### CODE REVIEW

**Comment by Y0ngg4n** [comment]
@jmshrv in the redesign issue was discussed to switch the menu button to the top. Maybe i will have time later that day to do this.

**Comment by Y0ngg4n** [comment]
@jmshrv now i switched it. Ready to merge :)

**Comment by Y0ngg4n** [comment]
Screenshot_2023-03-15-17-16-29-885_com unicornsonlsd finamp
@jmshrv looks like this now

**Comment by jmshrv** [comment]
Looks great, merged :)

**Comment by Chaphasilor** [comment]
Hold on, @Y0ngg4n. On the right side, the shuffle toggle and like button should be switched as well :) Should hopefully only take a minute or so...

Thanks!

**Comment by Y0ngg4n** [comment]
@Chaphasilor ah yeah thank you i will change that the next days

**Pull request merged**
