### PR TITLE
[Redesign] Brand New Queuing System ✨

### LINKED ISSUE #92: [Feature Request] Add an 'Up Next' Queue
In Spotify, when you play from a playlist, album, etc, it begins "Playing From xyz". Then, if you swipe on a song to add it to the queue it adds it to the "Up Next" section. Anything in Up Next gets played before the next item in Playing From.

I'd like to see this Up Next queue added to Finamp, so I can have a playlist running but queue songs to play next as I please.  Perhaps have a swipe left add to Up Next and a swipe right add to the bottom of the queue? (currently both directions add to the bottom of the queue)

### PR DESCRIPTION
**Pull request by Chaphasilor**
I can't believe this is finally in a state where I feel like we can think about getting this merged in.  
It was an absolute pain to implement this, and I'm barely happy with the end result, but it should be (much) better than the old queueing system, both functionality and design-wise.

Here's a quick break down:

- New `QueueService` for managing everything queue-related
- Queue is split into four parts: previous tracks, current track, next up, queue
- Support for adding tracks to "next up" (fixes #92)
  - Not affected by shuffle
- Consistent behavior (this was the most work)
- Quality of life improvements (show what playlists/album/etc. is currently playing = source)
- Improved queue design, with more functionality

### Screenshots

Screenshot_20230811-235039

Screenshot_20230812-000620

Screenshot_20230812-000620

### TODOs

- [x] Fix "shuffle always starts on first song" bug
- [x] Remove x and 3 dots icons, make list items dismissable and add long-press handler
- [x] Implement collapsible previous tracks? (like in redesign mockup)
- [x] Support starting playback at a specific index (e.g. when tapping on a track within an album or playlist)
- [x] Handle more playback sources (playlists show up as albums right now)
- [x] Go to parent item when tapping on the source string on the player screen
- [x] Support adding albums/playlists/etc. to queue or next up (shuffled or original order)
- [x] Finish up the design (dynamic colors, background, conditional rendering)
- [x] Finish up playback history view (basic functionality-wise, still needs a proper design through another PR)
- [x] Fix like button not having the correct state
- [x] Replace strings with localized versions
- [x] Add vibro-feedback for improved UX
- [x] Sticky list headers?
- [x] Add clear button for next up list
- [x] Improve Playback Reporting (based on #477)
- [x] Fix rewinding
- [x] Remove excessive debug logging and re-enable chopper logs
- [x] Use linear playback order for Instant Mixes (shuffle breaks song mixes, and the mix should be fully determined by Jellyfin anyway)
- [x] Fix label thickness
- [x] Reword "recently played" to "previous tracks"
- [x] Add "Album/Playlist/etc. added to Next Up" as source, handle it in the player header
- [x] Check if `minBufferDuration` is smaller than `maxBufferDuration`  
   - Otherwise the app needs to continuously fetch new data
- [x] Re-shuffle on shuffle enable (perhaps when turning shuffle *off* so that at the start it isn't shuffled twice)
- [x] Navigate to source when clicking on "Playing from" label (not working with single-track albums?)
- [x] Only show artist (not album artist) in queue panel
- [x] Add track to history when rewinding
- [x] Get rid of UI glitches (noticeable re-renders, delayed scrolling, etc.)
- [ ] Calculate accent color independent of specific screens or widgets
- [ ] Try to fix album cover when updating the queue(s) (@jmshrv)
- [ ] Test everything (I've been using various states of this implementation for many months now, but I'm just a single user)
- [ ] Re-enable reordering while shuffle is active, once https://github.com/ryanheise/just_audio/issues/1042 is fixed
- [x] ~~Implement light mode (once designed and contrast bug has been fixed)~~ - out of scope
- [ ] ~~Support playing next X songs (depending on settings) of songs tab, in current sorting order (recently added, artist, rating)~~ - out of scope
- [ ] ~~Add customization options~~ - out of scope

shoutout to @rom4nik, thanks a ton! <3

### CODE REVIEW

**Comment by AlperShal** [comment]
Features are looking awesome but I have a suggestion about the design. It's too complex. There are lots of buttons. I think instead of three dot and cross buttons, holding and swiping would be much better in the meaning of UX.

**Comment by Chaphasilor** [comment]
@AlperShal thanks for the suggestion. Long pressing for menu and swiping to remove will also be available, but these interactions have low discoverability, so I wanted to also offer a distinct button for the two actions.

Getting rid of one or two buttons would definitely leave more space for the title, but I'm not sure it this is a sacrifice worth making.  
Maybe it could be a setting, but I would like to avoid offering too much customization, because it's hard to support and hard to make look and work well in all configurations.

**Comment by AlperShal** [comment]
> @AlperShal thanks for the suggestion. Long pressing for menu and swiping to remove will also be available, but these interactions have low discoverability, so I wanted to also offer a distinct button for the two actions.
> 
> Getting rid of one or two buttons would definitely leave more space for the title, but I'm not sure it this is a sacrifice worth making.  
> Maybe it could be a setting, but I would like to avoid offering too much customization, because it's hard to support and hard to make look and work well in all configurations.

Yeah too much customization is definitely a problem to maintain on the long run so I wouldn't suggest it. But I think holding and swiping are pretty much global gestures. For example in WhatsApp, if you want to do something with a specific item like chat/group or a message you just hold it to have the options. Same is valid for Gmail, Discord, Element... In YouTube Music (probably Spotify too) the same is valid for every item (artist, album, song, queue item...). For the swiping part Gmail, contacts, and most of the media players (even Finamp itself right now) supports it. When using a queue it's clear that you will have the option to remove something from the queue. People will first try the swipe as a shortcut and if it doesn't work will try holding for having an options pop up. Such simple gestures has even became standart knowledge of using mobile phones/small screens. Maybe not a 50+ will grasp how to use these gestures but I don't think they will be using Jellyfin/Finamp for streaming content.

**Comment by Chaphasilor** [comment]
@AlperShal you're probably right, I'll take another look :)

**Comment by jmshrv** [comment]
I'll try my best to have a look through this (3000 lines!!), but thanks for all the work on this. I don't think I'd have been able to bring a massive change like this to completion. Hopefully my missed deadlines didn't annoy you too much 🙃

**Comment by jmshrv** [comment]
Swipe left to delete is a convention on iOS, but not on Android afaik

**Comment by Chaphasilor** [comment]
Switched to dismissing by swiping (both left or right) and long-pressing for the menu. See updated screenshots at the top.  
Also wanted to share a video, but turns out I broke something

**Comment by Chaphasilor** [comment]
After a finishing my last exam and some vacation, I'm back to finalizing this. I'll try to get this into a decent state as quickly as possible, because it will never be truly finished anyway...

**Comment by AlperShal** [comment]
> Improved the design by adding dynamic accent colors as well as the blurred cover. Updated screenshots are at the top. Let me know what you think, I can tweak the colors is needed...

I personally do not prefer dynamic colors in my themes/configs but still looks pretty nice. I don't see any problem. It's amazing to see how much time you are spending for this I am really thankful to you.

**Comment by Chaphasilor** [comment]
> I personally do not prefer dynamic colors in my themes/configs but still looks pretty nice

I'm planning on adding a default static accent color that can be switched to instead on the dynamic colors. Maybe that color could be customized as well, we will see. The theme is handled in another part of the app, so this implementation will support that out of the box 👍🏻  
And thanks for the kind words! <3

**Comment by AlperShal** [comment]
@jmshrv do you have any ETA for stable release including this PR?

**Comment by jmshrv** [comment]
> @jmshrv do you have any ETA for stable/unstable release including this PR?

We'd probably be able to start the redesign betas once this is merged :)

**Comment by kdltr** [comment]
@Chaphasilor been trying this for the past few days, great job!
The only friction I got was when trying to play multiple albums in a row. I couldn’t figure out how to queue them in the right order.
I would start by playing one, then press “play next” on the second one, and it would add it to next up, thus playing it at the end of the first track, instead of the first album.

**Comment by Chaphasilor** [comment]
@kdltr the button you're looking for is called "Add to Next Up", it inserts at the end of the Next Up queue 😁

In the long-press menu (when in the album list), the "Play Next" option is actually hidden while Next Up is empty, so that you can keep using the "Add to Next Up" button without thinking about it.

The buttons on the album page are temporary anyway, so they're not yet ideal...

**Comment by kdltr** [comment]
@Chaphasilor what I meant is that, when I play an album, it gets into the queue outside the Next Up. So when I add a new one, it’s added to the Next Up, which is between the track of the album I was playing and the rest of the album I was playing.

**Comment by kdltr** [comment]
@Chaphasilor A picture is worth a thousand words I guess :3
screenshot

**Comment by Chaphasilor** [comment]
Ahhh now I get it. Yeah I apparently forgot to add the button(s) for that... 👀  
I'll add them in a few hours 🙃

**Comment by Chaphasilor** [comment]
@kdltr I've added the buttons, let me know if everything works! And thanks for letting me know about the issue!

**Comment by Chaphasilor** [comment]
I'm still having issues with shuffling. When shuffle is active, manually skipping works just fine and skips to the correct track, but if you just let it play and the player skips automatically, it skips to the wrong track. This issue also exists with the current stable version of Finamp, and I have no idea why this is also happening here.  
If someone has any idea what could be happening I would be really grateful, as I've been chasing similar issues for months... 😕

**Comment by rom4nik** [comment]
>Can anyone try to reproduce this?

On 0.6.18:

https://github.com/jmshrv/finamp/assets/46846000/9c2d0801-14b3-4782-a5df-75a264c23364

**Comment by Chaphasilor** [comment]
@rom4nik thanks! can you also try with the version from this branch? I can send you the apk if you want me to :)

**Comment by AhegaHOE** [comment]
@rom4nik please consider activating the touch indicator in the developer settings. that would make it a lot easier to understand what you're doing in the video. 😎

**Comment by rom4nik** [comment]
Similar behavior on 5710e28cc74b4a1dbc3b1997c9d43b78978f9e90:


https://github.com/jmshrv/finamp/assets/46846000/14292c8e-c3cb-4898-b174-f1e3d20389a3

**Comment by Chaphasilor** [comment]
Okay I think I just found a "workaround". Try doing it again, but remove then remove *any* song from the queue. It should work properly now. I'm not sure why yet, but I think I can work with this and hopefully properly fix it soon.  
Could you please confirm that this workaround fixes it for you as well? :)

**Comment by Chaphasilor** [comment]
I managed to fix that issue, but now shuffling always starts on the first song again 🙃  
Let's see if I can find another way to fix that...

**Comment by Chaphasilor** [comment]
I only wanted to improve light theme support, but ended up also redesigning the Now Playing bar 😅

(design not final)

**Comment by AhegaHOE** [comment]
Currently when the Album Artist is very long it overflows the UI.

**Comment by Chaphasilor** [comment]
@AhegaHOE I just fixed all the overflow issues I could find. Let me know if I missed anything!

**Comment by AhegaHOE** [comment]
@Chaphasilor thank you. I'll take a look at it soon!

**Comment by jmshrv** [comment]
I've discussed it with Chaphasilor, and it looks like we can finally merge this :)

**Comment by Chaphasilor** [comment]
Holy. I thought the day would never come 😂😁

Thanks to everyone who tested and commented this! I'll try to get this to a beta level asap!

**Pull request merged**
