### PR TITLE
Add Gesture to swipe up to open the player

### PR DESCRIPTION
**Pull request by Y0ngg4n**
This adds a simple gesture to swipe up to open the player.

### CODE REVIEW

**Comment by Chaphasilor** [comment]
This is only triggered if the swipe starts on the mini player, right? Otherwise it would lead to problems when scrolling...

**Comment by Chaphasilor** [comment]
Awesome! Yeah that asymmetry has been bugging me from the start! Thanks for fixing it :)

**Comment by jmshrv** [comment]
Looks good, merging :)

**Comment by Y0ngg4n** [comment]
Thank you 🙂

**Pull request merged**
