### PR TITLE
Add redownload of failed tracks

### PR DESCRIPTION
**Pull request by Y0ngg4n**
Add simple redownload of failed Songs. This is more a workaround than fixing the real problem.

### CODE REVIEW

**Comment by arthurlutz** [comment]
Happy to test it out if there is an apk generated with that code.

**Comment by Y0ngg4n** [comment]
@arthurlutz i can generate you one if you want

**Comment by arthurlutz** [comment]
Thanks. Running the apk, but can't find the menu. I tried going to the list of Download Errors, but no icon there...

**Comment by Chaphasilor** [comment]
@arthurlutz looking at the code, it seems to *automatically* retry failed downloads. there is no menu (yet) :)

**Comment by Y0ngg4n** [comment]
@Chaphasilor no there should be a button at the download error list. there should be a refresh button. and if you press the refresh button it should open the menu to redownload them.

**Comment by Y0ngg4n** [comment]
@jmshrv thank you

**Comment by jmshrv** [comment]
No problem, just need to clean it up, and probably move it into DownloadHelper. Sorry for the delay 🙃

**Comment by Y0ngg4n** [comment]
No Problem 🙂

**Comment by jmshrv** [comment]
This should work now, I'll properly test in the morning. Merging :)

**Comment by arthurlutz** [comment]
I can confirm it works on the version pulled from fdroid ! Thanks !

**Pull request merged**
