### PR TITLE
Select transcoding segment container, default to fmp4

### LINKED ISSUE #600: Audio stuttering when transcode playing ogg vorbis on iOS
**Description**
When turning on the "Transcode" option in settings and playing Ogg Vorbis audio, the audio stutters.
When transcoding from other source formats this doesn't happen

**Media Information**
```
last
Container: ogg
Path: /Users/user/Music/test_music_lib/Arcaea All Songs/last.ogg
Size: 4 MB

Audio
Title: Last - VORBIS - Stereo
Codec: VORBIS
AVC: No
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 44100 Hz
Video range: Unknown
Video range type: Unknown
Default: No
Forced: No
External: No

Image
Codec: MJPEG
AVC: No
Profile: Baseline
Resolution: 768x768
Bit depth: 8 bit
Video range: Unknown
Video range type: Unknown
Color space: bt470bg
Pixel format: yuvj444p
Ref frames: 1
```

### PR DESCRIPTION
**Pull request by Chaphasilor**
This should hopefully fix #600, and maybe some other issues too.

Seems to work on Android (14), but it would be good if someone could give this a try on iOS and test with a Vorbis file to make sure this is indeed a fix.  

Either way, it probably doesn't hurt to include this setting, even if it doesn't fix the issue.

### CODE REVIEW

**Comment by felix920506** [comment]
If I remember correctly there should be extra checks to prevent selecting MP3 codec with fMP4 container because that won't work on most devices.

Opus can also be streamed on newer iOS versions using fMP4 containers

**Comment by Chaphasilor** [comment]
@felix920506 thanks for the heads up! Right now Finamp only ever uses AAC for transcoding anyway, except for transcoded downloads (but those aren't streamed anyway). So this shouldn't be a problem.  
Opus streaming on iOS sounds very interesting though! If there aren't any major issues with the fmp4 containers we could add more codec options for streaming in a future release.

@jmshrv did you manage to give this a quick test yet?

**Comment by jmshrv** [comment]
This got lost in my emails sorry, will test :)

**Comment by felix920506** [comment]
Is there any update on this PR? Or is there anything I can do to help?

**Comment by Chaphasilor** [comment]
@felix920506 I still haven't heard from anyone who tested this on iOS, so if you could manage to do that, it would definitely help!

**Comment by felix920506** [comment]
@Chaphasilor i tried launching it in Xcode emulator but it just simply won't start, both the rewrite branch and this branch

**Comment by Chaphasilor** [comment]
@felix920506 have you looked through [CONTRIBUTING.md](https://github.com/jmshrv/finamp/blob/main/CONTRIBUTING.md)? Maybe there's some additional setup required that you haven't done yet?  
Any error messages would also help. Are you using VS Code for development? The application logs should appear in the debug console when launching the app through the debugger

**Comment by felix920506** [comment]
@Chaphasilor I'm using IntelliJ Idea, I'll check the document again and report back

**Comment by felix920506** [comment]
@Chaphasilor I am getting this error when I try to launch it in Xcode emulator
截圖 2024-10-31 下午2 27 43

**Comment by felix920506** [comment]
Update: I was able to get into the main screen and settings after deleting the app from the emulator and rerunning it. The settings show up as expected. I will test playback later.
截圖 2024-10-31 下午2 32 03

**Comment by felix920506** [comment]
@Chaphasilor I tested playback on iOS in the Xcode emulator, iOS 18.0. Here are the results:
- Playback starts normally and plays without issues.
- Stuttering in ogg vorbis files no longer occurs.
- Server logs show transcodes are correctly using .mp4 segments

**Comment by Chaphasilor** [comment]
Thanks for testing! I guess we can merge this then ^^

Now that DirectStreaming dropped with 10.10, do you think it might be worthwhile to add support for that, so we could use TS and fmp4 transports even when not transcoding?

**Comment by felix920506** [comment]
@Chaphasilor we could just move to using the UniversalAudio endpoint and the server will auto decide whether to send the source file or do a transcode.

**Comment by Chaphasilor** [comment]
How does it decide? Is there documentation about that? 🙃

**Comment by felix920506** [comment]
It would probably be faster to ask on matrix

**Comment by felix920506** [comment]
Is there anything holding this from getting merged?

**Comment by Chaphasilor** [comment]
Nope, just forgot about it while waiting for the automatic tests to finish ^^  
Thanks for the reminder :D

**Pull request merged**
